// Import database connection pool
const db = require("../config/db");

// ─────────────────────────────────────────────────────────────────────────
// 💰 REVENUE REPORT
// ─────────────────────────────────────────────────────────────────────────

// Total revenue (all-time) — only counts rows where status = 'paid'
const getTotalRevenue = () => {
  return db.query(`
    SELECT COALESCE(SUM(amount_received), 0) AS total_revenue
    FROM payments
    WHERE status = 'paid'
  `);
};

// Revenue for the current calendar month (based on created_at)
const getRevenueThisMonth = () => {
  return db.query(`
    SELECT COALESCE(SUM(amount_received), 0) AS revenue_this_month
    FROM payments
    WHERE status = 'paid'
      AND YEAR(created_at) = YEAR(CURDATE())
      AND MONTH(created_at) = MONTH(CURDATE())
  `);
};

// Revenue grouped by month for the last N months (default 6) — based on created_at
const getRevenueByMonth = (months = 6) => {
  return db.query(
    `
    SELECT
      DATE_FORMAT(created_at, '%Y-%m') AS month_key,
      DATE_FORMAT(created_at, '%b %Y') AS month_label,
      COALESCE(SUM(amount_received), 0) AS revenue
    FROM payments
    WHERE status = 'paid'
      AND created_at >= DATE_SUB(CURDATE(), INTERVAL ? MONTH)
    GROUP BY month_key, month_label
    ORDER BY month_key ASC
  `,
    [months]
  );
};

// Revenue within a custom date range (inclusive), based on created_at date
const getRevenueByDateRange = (startDate, endDate) => {
  return db.query(
    `
    SELECT COALESCE(SUM(amount_received), 0) AS revenue
    FROM payments
    WHERE status = 'paid'
      AND DATE(created_at) BETWEEN ? AND ?
  `,
    [startDate, endDate]
  );
};

// ─────────────────────────────────────────────────────────────────────────
// 📦 MEMBERSHIP REPORT
// ─────────────────────────────────────────────────────────────────────────

// Per-package breakdown: package name, member count (distinct users with that
// package in payments), and total revenue generated by that package
const getPackageBreakdown = () => {
  return db.query(`
    SELECT
      pkg.id AS package_id,
      pkg.name AS package_name,
      COUNT(DISTINCT p.user_id) AS member_count,
      COALESCE(SUM(CASE WHEN p.status = 'paid' THEN p.amount_received ELSE 0 END), 0) AS revenue
    FROM packages pkg
    LEFT JOIN payments p ON p.package_id = pkg.id
    GROUP BY pkg.id, pkg.name
    ORDER BY revenue DESC
  `);
};

// ─────────────────────────────────────────────────────────────────────────
// 📈 TRENDS & ANALYTICS
// ─────────────────────────────────────────────────────────────────────────

// Monthly growth = new memberships per month (based on memberships.created_at)
const getNewMembershipsByMonth = (months = 6) => {
  return db.query(
    `
    SELECT
      DATE_FORMAT(created_at, '%Y-%m') AS month_key,
      DATE_FORMAT(created_at, '%b %Y') AS month_label,
      COUNT(*) AS new_members
    FROM memberships
    WHERE created_at >= DATE_SUB(CURDATE(), INTERVAL ? MONTH)
    GROUP BY month_key, month_label
    ORDER BY month_key ASC
  `,
    [months]
  );
};

// Revenue comparison between consecutive months (reuses revenue-by-month data,
// growth % is computed in the controller to keep SQL simple)
const getRevenueTrend = (months = 6) => getRevenueByMonth(months);

module.exports = {
  getTotalRevenue,
  getRevenueThisMonth,
  getRevenueByMonth,
  getRevenueByDateRange,
  getPackageBreakdown,
  getNewMembershipsByMonth,
  getRevenueTrend,
};